steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/django_web_app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/django_web_app']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/django_web_app', 'django_web_app=gcr.io/$PROJECT_ID/django_web_app', '--namespace=default']
images:
- 'gcr.io/$PROJECT_ID/django_web_app'
options:
  logging: 'NONE'

