apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-web-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-web-app
  template:
    metadata:
      labels:
        app: django-web-app
    spec:
      containers:
      - name: django-web-app
        image: gcr.io/internship-tasks-428019/django-web-app
        ports:
        - containerPort: 8080
