apiVersion: v1
kind: Service
metadata:
  name: django-web-app
spec:
  selector:
    app: django-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
