apiVersion: v1
kind: Service
metadata:
  name: django_web_app
spec:
  selector:
    app: django_web_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
